
/**
 * @seunoyeniyi
 * @jesulonimii - I added this file to make it easier to change the default validator messages
 * @warning - Do not edit this file unless you know what you are doing
 * */



const ValidatorMessages = {
    'required': 'The {{ field }} field is required',
    'email': 'The {{ field }} field must be a valid email address',
    'unique': 'The {{ field }} provided already exists',
    'min': 'The {{ field }} field must be at least {{ options.min }}',
    'max': 'The {{ field }} field must be less than {{ options.max }}',
    'above': 'The {{ field }} field must be above {{ options.above }}',
    'under': 'The {{ field }} field must be under {{ options.under }}',
    'confirmed': 'The {{ field }} field confirmation does not match',
    'alpha': 'The {{ field }} field must be a valid alpha string',
    'alphaNumeric': 'The {{ field }} field must be a valid alpha numeric string',
    'array': 'The {{ field }} field must be a valid array',
    'boolean': 'The {{ field }} field must be a valid boolean',
    'date': 'The {{ field }} field must be a valid date',
    'dateFormat': 'The {{ field }} field must be a valid date in {{ options.format }} format',
    'enum': 'The {{ field }} field must be one of {{ options.choices }}',
    'enumSet': 'The {{ field }} field must be one of {{ options.choices }}',
    'exists': 'The {{ field }} field does not exists',
    'different': 'The {{ field }} field must be different than {{ options.field }}',
    'in': 'The {{ field }} field must be one of {{ options.choices }}',
    'notIn': 'The {{ field }} field must not be one of {{ options.choices }}',
    'integer': 'The {{ field }} field must be a valid integer',
    'decimal': 'The {{ field }} field must be a valid decimal',
    'float': 'The {{ field }} field must be a valid float',
    'object': 'The {{ field }} field must be a valid object',
    'number': 'The {{ field }} field must be a valid number',
    'string': 'The {{ field }} field must be a valid string',
    'same': 'The {{ field }} field must be the same as {{ options.field }}',
    'size': 'The {{ field }} field must be equal to {{ options.size }}',
    'url': 'The {{ field }} field must be a valid url',
    'regex': 'The {{ field }} field format is invalid',
    'after': 'The {{ field }} field must be after {{ options.after }}',
    'afterOffsetOf': 'The {{ field }} field must be after {{ options.afterOffsetOf }}',
    'before': 'The {{ field }} field must be before {{ options.before }}',
    'beforeOffsetOf': 'The {{ field }} field must be before {{ options.beforeOffsetOf }}',
    'requiredIfExists': 'The {{ field }} field is required',
    'requiredIfExistsAll': 'The {{ field }} field is required',
    'requiredIfExistsAny': 'The {{ field }} field is required',
    'requiredIfNotExists': 'The {{ field }} field is required',
    'requiredIfNotExistsAll': 'The {{ field }} field is required',
    'requiredIfNotExistsAny': 'The {{ field }} field is required',
}

export default ValidatorMessages